name: finapp
recipe: drupal9
config:
  framework: drupal9
  php: '7.3'
  via: apache
  webroot: .
  database: mysql
  drush: ^9
  xdebug: false
  cache: true
  conf:
    php: .vscode/php.ini
services:
  appserver:
    build:
      - composer install
    xdebug: debug
    config:
      php: .vscode/php.ini
  myservice:
    type: php
    build_as_root:
      - sudo apt-get install php-gd


