charts_default_settings:
  library: highcharts
  type: bar
  title: 'Chart Name'
  colors:
    - '#2f7ed8'
    - '#0d233a'
    - '#8bbc21'
    - '#910000'
    - '#1aadce'
    - '#492b6e'
    - '#f28f43'
    - '#77a1e5'
    - '#c42525'
    - '#a6c96a'
  title_position: out
  tooltips: 'TRUE'
  data_labels: 'TRUE'
  data_markers: 'TRUE'
  legend_position: right
  background: ''
  three_dimensional: 0
  polar: 0
  width: ''
  width_units: '%'
  height: ''
  height_units: px
  max: '100'
  min: '0'
  green_from: '85'
  green_to: '100'
  yellow_from: '50'
  yellow_to: '85'
  red_from: '0'
  red_to: '50'
  xaxis_title: 'Horizontal Title'
  xaxis_labels_rotation: '0'
  yaxis_title: 'Vertical Title'
  yaxis_min: '0'
  yaxis_max: '100'
  yaxis_prefix: $
  yaxis_suffix: ''
  yaxis_decimal_count: ''
  yaxis_labels_rotation: '0'
