_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  alex_custom: 0
  asset_injector: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  charts: 0
  charts_api_example: 0
  charts_billboard: 0
  charts_blocks: 0
  charts_c3: 0
  charts_chartjs: 0
  charts_google: 0
  charts_highcharts: 0
  ckeditor: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  feeds: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonapi: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  replicate: 0
  replicate_ui: 0
  rest: 0
  search: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_aggregator: 0
  views_aggregator_more_functions: 0
  views_ui: 0
  workflows: 0
  ds: 1
  ds_extras: 2
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  adminimal_theme: 0
  claro: 0
  gin: 0
  mytheme: 0
profile: standard
