<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help()
 */
function hello_world_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.hello_world':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This is an example module.') . '</p>';
            return $output;

        default:
    }
}


/*
* Implements hook_mail()
*/
function hello_world_mail($key, &$message, $params){
    switch ($key){
        case 'hello_world_log':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = t('There is an error on your website');
            $message['body'][] = $params['message'];

            break;
    }
}


function hello_world_form_salutation_configuration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){

    
    $form['color'] = [
        '#type' => 'color',
        '#title' => t('Calendar Color'),
        '#default_value' => '#ffffff',
    ];
	$form['phone'] = array(
		'#title' => t('Your phone'),
		'#type' => 'textfield',
	);

    // return $form;

    
    // return parent::buildForm($form, $form_state);
}